### ISSUE TITLE
ShmQueue 应该不是线程安全的

### ISSUE THREAD

**Issue by bruan** [mikewei/shm_container#1]
看了下ShmQueue 应该不是线程安全的，即使在单读单写下，问题出在你用一个volatile变量在控制一块内存，C++里面volatile只保证每次取值一定是去内存那边取，但是指令乱序没有保证的，在x86架构下，可能这个代码不会跑出问题，但是在其他（arm，power）这样的架构下很容易跑出问题，所以为了安全起见，还是用c++11的atomic吧。

**Comment by mikewei** [comment]
这个库设计实现时的确是明确针对服务端、针对x86架构的，具体的说是在支持aligned 64bit原子操作以及 Total Store Ordering内存模型的架构上可以保证无锁的并发安全，Release-Acquire ordering在不做多余操作下可以保证。 因为设计目标原因，并不打算加上繁多的atomic代码以支持任意Relax Ordering内存模型，后续会在文档和代码中突出一下这个约束吧。
