### ISSUE TITLE
hashmap KeyType 定义为 std::string 报错

### ISSUE THREAD

**Issue by 0x01toby** [mikewei/shm_container#3]
shmc/shm_hash_map.h:288:24: error: cannot bind ‘const volatile std::__cxx11::basic_string<char>’ lvalue to ‘std::__cxx11::basic_string<char>&&’

**Comment by mikewei** [comment]
如文档中所说目前KeyType只支持POD等StandardLayout类型:-(
后续支持std::string在考虑中。目前如果要在key中使用字符串，可能需要定义一个结构体并限制字符串最大长度
