### ISSUE TITLE
hash_map 获取数据问题

### ISSUE THREAD

**Issue by vbirds** [mikewei/shm_container#4]
hash_map 每次获取数据Find接口都是对原数据的一次拷贝，是否可设计成获取源数据，让使用者操作数据。比如我存入一个结构体，想修改里面的值，需要Find接口拷贝数据到std::sting 再通过指针转换成定义的结构体修改完数据后再replace 拷贝一次数据，这样是不是太麻烦了

**Comment by mikewei** [comment]
接口需要设计成拷贝，为了实现并发的安全
