### ISSUE TITLE
shm_hash_map 多进程问题

### ISSUE THREAD

**Issue by yangqun** [mikewei/shm_container#5]
请教下，一个进程去写：
shmc::ShmHashMap<const char *, shmc::POSIX> hash_map_;
    shmc::POSIX alloc_;
    hash_map_.InitForWrite(kShmKey, kKeyNum, kNodeSize, kNodeNum);
    const char *key = "testkey";
    while(1){
        hash_map_.Replace(key, value.c_str());
        sleep(1);
    }
然后另外一个进程去读，
shmc::ShmHashMap<const char *, shmc::POSIX> hash_map_;
    shmc::POSIX alloc_;
    hash_map_.InitForRead(kShmKey);
    const char *key = "testkey";
    while(1){
        std::string out;
        if(hash_map_.Find(key, &out)){
            printf("%s\n",out.c_str());
        }
        sleep(1);
}

但是为啥读的那个进程一直提示
ShmHashMap::Find: key not found
哪里出了问题呢？

**Comment by mikewei** [comment]
不能Key的实例化类型不能是指针类型，指针仅在自已进程内有意义，无法跨进程共享
