### ISSUE TITLE
ShmSyncBuf<Alloc>::InitForWrite创建时参数检查BUG

### ISSUE THREAD

**Issue by zpr977** [mikewei/shm_container#6]
原代码如下：
----------------------------------------------------------------------------------------
bool ShmSyncBuf<Alloc>::InitForWrite(const std::string& shm_key,
                                     size_t buf_size_bytes) {
  // .......
  if (buf_size_bytes < (kOverwriteBufferSize * 2)
      && buf_size_bytes > 0x800000000UL /* 2^32 x 8B */) {  
    SHMC_ERR_RET("ShmSyncBuf::InitForWrite: invalid buf_size_bytes\n");
  }
  // .......
}
-----------------------------------------------------------------------------------------
**if (buf_size_bytes < (kOverwriteBufferSize * 2) && buf_size_bytes > 0x800000000UL /* 2^32 x 8B */)** 这里 && 做判断值应该时存在BUG的，作者想对入参buf_size_bytes做校验，应该需要用 ||

**Comment by mikewei** [comment]
是bug，谢谢反馈
